config/routes.rb
Alxs::Application.routes.draw do
  match '/contact',     to: 'contacts#new',             via: 'get'
  resources "contacts", only: [:new, :create]  
  match '/help', to: 'main#help', via: 'get'
  match '/about', to: 'main#about', via: 'get'
  match '/blog', to: 'main#blog', via: 'get'
  match '/privacy', to: 'main#privacy', via: 'get'
  match '/terms', to: 'main#terms', via: 'get'
  match '/feedback', to: 'main#feedback', via: 'get'
  match '/jobs', to: 'main#jobs', via: 'get'
  root 'main#home'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :number, :validate => true
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "alex.scott@tipsforthings.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def blog
  end

  def privacy
  end

  def terms
  end

  def chat
  end

  def jobs
  end

  def feedback
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "ALXS"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  def nav_link(link_text, link_path)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, :class => class_name) do
    link_to link_text, link_path
  end
end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<% provide(:title, 'Contact Me') %>
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
<h2 class="three-em orange-text remove-border uppercase">Send me a message</h2>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :number, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary contact-button" %>
    </div>
  <% end %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
<div class="container">
<small>
<a href="http://alxs.co.uk">ALXS</a> designed by <u>Alex Scott</u>
</small>
<nav>
<ul class="hidden">
<li><%= link_to "Privacy", privacy_path %></li>
<li><%= link_to "Terms", terms_path %></li>
</ul>
</nav>
</div>
</div>

app/views/layouts/_header.html.erb
 <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# profile: http://ogp.me/ns/profile#">
<meta property="fb:profile_id" content="https://www.facebook.com/djalexscott" /> 
<meta property="og:type"   content="profile" /> 
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<meta property="og:title" content="My Online Profile & Portfolio" />
<meta property="og:site_name" content="ALXS" />
<meta property="og:image" content="http://alxs.co.uk/assets/alxs.jpg" />
<meta property="og:url" content="http://alxs.co.uk" <link rel="author" href="https://plus.google.com/u/0/116471654573031381012/about"/>
<meta property="og:description" content="Everything about ALXS, including my background, portfolio and services that I can offer." />
<meta property="og:image:width" content="1350" />
<meta property="og:image:height" content="608" /><title><%= full_title(yield(:title)) %></title>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
<%= render 'layouts/shim' %>
<link href="/assets/sticky-footer.css" rel="stylesheet">
<link href="/assets/custom.css" rel="stylesheet">
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Lobster+Two:400italic,700' rel='stylesheet' type='text/css'>
 <%= javascript_include_tag :modernizr %>
 </head>

app/views/layouts/_navigation.html.erb
      <div class="navbar navbar-fixed-top navbar-inverse">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".navbar-offcanvas" data-canvas="body">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="/">ALXS</a>
      </div>
      <div class="navbar-offcanvas offcanvas navmenu-fixed-left pull-right">
        <a class="navmenu-brand" href="/">ALXS</a>
          <ul class="nav navbar-nav">
            <%= nav_link "Home",    root_path %>
            <%= nav_link "About",    about_path %>
            <%= nav_link "Contact",    contact_path %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_social.html.erb
<div class="social-toolbar">
  <a class="btn btn-social-icon btn-facebook" href="https://www.facebook.com/djalexscott" target="_blank" alt="ALXS on Facebook">
    <i class="fa fa-facebook"></i>
  </a>
  <a class="btn btn-social-icon btn-github" href="https://github.com/tipsforthings" target="_blank" alt="ALXS (Tips for Things) on Github">
    <i class="fa fa-github"></i>
  </a>
  <a class="btn btn-social-icon btn-google-plus" href="https://plus.google.com/u/0/116471654573031381012/about" target="_blank" alt="ALXS on Google+">
    <i class="fa fa-google-plus"></i>
  </a>
  <a class="btn btn-social-icon btn-twitter" href="https://twitter.com/djalexscott" target="_blank" alt="ALXS on Twitter">
    <i class="fa fa-twitter"></i>
  </a>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<html>
<%= render 'layouts/header' %>
<body class="dark-body loading">
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
<div class="container container-main">
<%= render 'layouts/navigation' %>
<%= yield %>
<div class="social-container container-xs-height">
<%= render 'layouts/social' %>
</div>
</div>
<%= render 'layouts/footer' %>
  <%= javascript_include_tag :application %>
</body>
</html>

app/views/main/about.html.erb
<% provide(:title, 'About') %>
  <div class="row">
    <div class="col-md-6">
<h2 class="three-em orange-border">Let's start with the name...</h2>
</div>
    <div class="col-md-6">
    </div>
  </div>
<p class="three-em justify-text dark-p">
My real name is Alex Scott - ALXS being short for "Alex S". The ALXS came from gaming and music, as with both I was behind this alias. The name stuck sort-of, so I decided to use the name for my web site. The reason behind this, is Rule #1 of choosing a domain name, is that it should ideally be short and rememerable. I beleive that this domain name fits into both categories. 
</p>


  <div class="row border-top">
    <div class="col-md-4 right-align">
      <div class="whoiam">
<h2 class="who">What<br/>I <span><br />do</span></h2>
</div>

    </div>
    <div class="col-md-8">
<p class="three-em top-ten justify-text ">
I specialise in HTML and CSS, however I am currently learning Rails 4. This site is infact running on Rails.
</p>
<p class="three-em justify-text">
I can provide the solution required by the client, whether it's a single-page web presence for your business, an online store or a fully-fledged CMS with social features. If the client already has a team of developers or designers, I can work as part of that team to get a site or web app from the design phase to deployment. 
</p>


  </div>


</div>
  <div class="row border-top">
    <div class="col-md-8">
<p class="three-em justify-text top-twenty">
If you would like a site that is requires regular updating, I can also do this. A time frame for the content to be updated would be minimal and the site would remain online 100% of the time, whether it's a minor change or a major site overhaul.</p>
<p class="three-em justify-text">If the client would like to update the content themselves but would not consider themselves 'tech-savvy', one to one sessions can be provided to the client, describing the proceedures for updating the content on the site - which is by no means a difficult task. In fact it is as easy as setting a reminder in your phone or adding an appointment to calendar software.
</p>
  </div>
    <div class="col-md-4 left-align">
      <div class="whoiam">
<h2 class="who"><span>Going</span><br />the extra<br />mile</h2>
</div>

    </div>



</div>
<p class="three-em justify-text top-twenty border-top">
Going beyond web design, I can setup a server with the appropriate services and software to run the clients website or webapp. From a simple website server to sophisticated shoutcast or flash video servers, I can set it up with performance and security in mind.</p>
<p class="three-em justify-text">Alongside the website or other server software, the client will also have personal, branded email address, with a simple admin panel for website owners to add and remove user emails as required. The email accounts are easily syncronised to any smartphone or desktop software that the client or their users would like to use.
</p>
<p class="three-em justify-text top-twenty border-top dark-p">
If you think that you could require any of these services, whether it's a small one-time job, or an offer of a larger job or regular work, please do not hesitate to get in touch via the contact page or through my social media profiles.
</p>

app/views/main/blog.html.erb
<% provide(:title, 'Blog') %>
<h1>Main#blog</h1>
<p>Find me in app/views/main/blog.html.erb</p>

app/views/main/chat.html.erb
<h1>Main#chat</h1>
<p>Find me in app/views/main/chat.html.erb</p>

app/views/main/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Main#contact</h1>
<p>Find me in app/views/main/contact.html.erb</p>

app/views/main/feedback.html.erb
<h1>Main#feedback</h1>
<p>Find me in app/views/main/feedback.html.erb</p>

app/views/main/help.html.erb
<h1>Main#help</h1>
<p>Find me in app/views/main/help.html.erb</p>

app/views/main/home.html.erb
<div class="center jumbotron ">
<h1 class="three-em">ALXS</h1>

</div>
<div class="row">

    <div class="col-md-4">
<div>
        <h2 class="frontpage">Design</h2>
</div>
    </div>
    <div class="col-md-4">
<div>
        <h2 class="frontpage">Build</h2>
</div>
    </div>
    <div class="col-md-4">
<div>
        <h2 class="frontpage">Deploy</h2>
</div>
    </div>
</div>

app/views/main/jobs.html.erb
<h1>Main#jobs</h1>
<p>Find me in app/views/main/jobs.html.erb</p>

app/views/main/privacy.html.erb
<h1>Main#privacy</h1>
<p>Find me in app/views/main/privacy.html.erb</p>

app/views/main/terms.html.erb
<h1>Main#terms</h1>
<p>Find me in app/views/main/terms.html.erb</p>